title: Liam Daly
description: Notes and Thoughts
url: "https://ldaly14.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name   : "Liam Daly"
  avatar : ""
  bio    : "bio"
  location: "University of Michigan"
  email  : "liamdaly@umich.edu"

