title: Liam Daly
description: Notes and Thoughts
url: "https://ldaly14.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

header_pages:
  - index.md
  - research.md
  - CV.md
  - photos.md
  - notes.md
  - reading.md

author:
  name   : "Liam Daly"
  avatar : ""
  bio    : ""
  location: ""
  email  : ""

