title: Liam Daly
description: Notes and Thoughts
url: "https://ldaly14.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      css: "/css/custom.css"

author:
  name   : "Liam Daly"
  avatar : "/images/Liam_Daly.jpg"
  bio    : "Physics PhD Candidate | Cold Atom Experimentalist"
  location: "University of Michigan"
  email  : "liamdaly@umich.edu"

