title: Liam Daly
description: Notes and Thoughts
url: "https://ldaly14.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

sass:
  style: compressed

author:
  name   : "Liam Daly"
  avatar : "/images/Liam_Daly.jpg"
  bio    : "Physics PhD Candidate and Cold Atom Experimentalist"
  location: "University of Michigan"
  email  : "liamdaly@umich.edu"

